# SITE CONFIGURATION
title: **James Babyak** | Data Science
author: GitHub User | babyakja
description: > # Meta description of Homepage
  I’m an aspiring data scientist who isn’t shy about tackling critical issues. 
  I have always been fascinated by numbers and patterns and use this ability to extract insight and knowledge from hidden details. 
  By using my intuition and skill, I look to see what the data can tell us, and strive to get it to collaborate with the right people to make a positive impact in the world. 
  The truth is in the details, let’s work together.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://babyakja.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: James Babyak
  links:
    - https://twitter.com/jamm_babyak
    - https://www.linkedin.com/in/james-babyak
    - https://github.com/babyakja

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Data Scientist for Positive Impact

hero_img: /posts/sleek_lg.jpg  # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: james.babyak@gamil.com # email for form submission

twitter_username: jamm_babyak # replace with your_twitter_username or comment to remove link from footer
github_username:  babyakja # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
